version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mongodb